apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: database
  name: database
  namespace: chat-app
spec:
  replicas: 1
  serviceName: "database-service"
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: database
    spec:
      containers:
      - image: mongo
        name: mongo
        resources: {}
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: root
